/**
 * Seed vocabulary for the German flashcard app.
 * Progress (status / lastReviewedAt) is stored separately in localStorage.
 * Custom/imported words are stored under wortkarte.custom.v1.
 */
window.SEED_WORDS = [
  // --- 54 from notebook import ---
  {
    id: "schlussendlich",
    german: "schlussendlich",
    english: "finally / ultimately",
    exampleDe: "Schlussendlich haben wir uns für den günstigeren Plan entschieden.",
    exampleEn: "Ultimately, we decided on the cheaper plan.",
  },
  {
    id: "endlich",
    german: "endlich",
    english: "finally",
    exampleDe: "Endlich ist das Projekt fertig.",
    exampleEn: "The project is finally finished.",
  },
  {
    id: "absicht",
    german: "Absicht",
    english: "intention",
    exampleDe: "Das war nicht meine Absicht.",
    exampleEn: "That was not my intention.",
  },
  {
    id: "ursachen",
    german: "Ursachen",
    english: "causes",
    exampleDe: "Wir müssen die Ursachen des Problems finden.",
    exampleEn: "We have to find the causes of the problem.",
  },
  {
    id: "anbieten",
    german: "anbieten",
    english: "to offer",
    exampleDe: "Darf ich Ihnen etwas zu trinken anbieten?",
    exampleEn: "May I offer you something to drink?",
  },
  {
    id: "faehigkeiten",
    german: "Fähigkeiten",
    english: "skills / abilities",
    exampleDe: "Ihre sprachlichen Fähigkeiten sind sehr gut.",
    exampleEn: "Your language skills are very good.",
  },
  {
    id: "taetigkeiten",
    german: "Tätigkeiten",
    english: "activities",
    exampleDe: "Zu meinen Tätigkeiten gehört auch die Kundenberatung.",
    exampleEn: "My activities also include customer consulting.",
  },
  {
    id: "rat-und-tat",
    german: "Rat und Tat",
    english: "tips and tricks / advice and practical help",
    exampleDe: "Er steht mir mit Rat und Tat zur Seite.",
    exampleEn: "He supports me with advice and practical help.",
  },
  {
    id: "einstellung",
    german: "Einstellung",
    english: "attitude (internal)",
    exampleDe: "Eine positive Einstellung hilft in schwierigen Situationen.",
    exampleEn: "A positive attitude helps in difficult situations.",
  },
  {
    id: "ausstrahlung",
    german: "Ausstrahlung",
    english: "presence / aura (external)",
    exampleDe: "Sie hat eine ruhige Ausstrahlung.",
    exampleEn: "She has a calm presence.",
  },
  {
    id: "allgemein",
    german: "allgemein",
    english: "general / generally",
    exampleDe: "Allgemein bin ich mit dem Ergebnis zufrieden.",
    exampleEn: "Generally, I am satisfied with the result.",
  },
  {
    id: "genauigkeit",
    german: "Genauigkeit",
    english: "accuracy",
    exampleDe: "Bei diesem Bericht kommt es auf Genauigkeit an.",
    exampleEn: "Accuracy matters in this report.",
  },
  {
    id: "ausfuehrlich",
    german: "ausführlich",
    english: "detailed / thorough",
    exampleDe: "Bitte beschreiben Sie das Problem ausführlich.",
    exampleEn: "Please describe the problem in detail.",
  },
  {
    id: "zufaellig",
    german: "zufällig",
    english: "by chance / accidental",
    exampleDe: "Ich habe sie zufällig im Zug getroffen.",
    exampleEn: "I met her by chance on the train.",
  },
  {
    id: "gestalten",
    german: "gestalten",
    english: "to shape / to design",
    exampleDe: "Wir wollen den Prozess neu gestalten.",
    exampleEn: "We want to redesign the process.",
  },
  {
    id: "wachsen",
    german: "wachsen",
    english: "to grow",
    exampleDe: "Das Unternehmen wächst jedes Jahr.",
    exampleEn: "The company grows every year.",
  },
  {
    id: "verantwortung",
    german: "Verantwortung",
    english: "responsibility",
    exampleDe: "Ich übernehme die Verantwortung für dieses Projekt.",
    exampleEn: "I take responsibility for this project.",
  },
  {
    id: "beitragen",
    german: "beitragen",
    english: "to contribute",
    exampleDe: "Jeder kann zum Erfolg beitragen.",
    exampleEn: "Everyone can contribute to success.",
  },
  {
    id: "beeinflussen",
    german: "beeinflussen",
    english: "to influence",
    exampleDe: "Werbung kann Kaufentscheidungen beeinflussen.",
    exampleEn: "Advertising can influence purchasing decisions.",
  },
  {
    id: "entwickeln",
    german: "entwickeln",
    english: "to develop",
    exampleDe: "Wir entwickeln eine neue Strategie.",
    exampleEn: "We are developing a new strategy.",
  },
  {
    id: "uebernehmen",
    german: "übernehmen",
    english: "to take on / to take over",
    exampleDe: "Kannst du diese Aufgabe übernehmen?",
    exampleEn: "Can you take on this task?",
  },
  {
    id: "steuerung",
    german: "Steuerung",
    english: "control / steering",
    exampleDe: "Die Steuerung des Projekts liegt bei der Projektleitung.",
    exampleEn: "Control of the project lies with the project lead.",
  },
  {
    id: "umsetzung",
    german: "Umsetzung",
    english: "implementation",
    exampleDe: "Die Umsetzung des Plans beginnt nächste Woche.",
    exampleEn: "Implementation of the plan begins next week.",
  },
  {
    id: "entwerfen",
    german: "entwerfen",
    english: "to design / to draft",
    exampleDe: "Sie entwirft ein neues Logo für die Firma.",
    exampleEn: "She is designing a new logo for the company.",
  },
  {
    id: "umfeld",
    german: "Umfeld",
    english: "environment / surroundings",
    exampleDe: "Ein ruhiges Umfeld hilft beim Lernen.",
    exampleEn: "A quiet environment helps with learning.",
  },
  {
    id: "verlaessliche",
    german: "verlässliche",
    english: "reliable",
    exampleDe: "Wir brauchen verlässliche Informationen.",
    exampleEn: "We need reliable information.",
  },
  {
    id: "bestehen",
    german: "bestehen",
    english: "to exist / to pass / to consist",
    exampleDe: "Die Prüfung besteht aus drei Teilen.",
    exampleEn: "The exam consists of three parts.",
  },
  {
    id: "detailliert",
    german: "detailliert",
    english: "detailed",
    exampleDe: "Bitte senden Sie mir eine detaillierte Übersicht.",
    exampleEn: "Please send me a detailed overview.",
  },
  {
    id: "unterstuetzen-bei",
    german: "unterstützen bei",
    english: "to support with",
    exampleDe: "Ich unterstütze dich bei der Vorbereitung.",
    exampleEn: "I support you with the preparation.",
  },
  {
    id: "selbststaendigkeit",
    german: "Selbständigkeit",
    english: "independence",
    exampleDe: "Selbständigkeit ist in diesem Beruf sehr wichtig.",
    exampleEn: "Independence is very important in this job.",
  },
  {
    id: "noetig",
    german: "nötig",
    english: "necessary",
    exampleDe: "Ist das wirklich nötig?",
    exampleEn: "Is that really necessary?",
  },
  {
    id: "dauer",
    german: "Dauer",
    english: "duration",
    exampleDe: "Die Dauer des Kurses beträgt sechs Wochen.",
    exampleEn: "The duration of the course is six weeks.",
  },
  {
    id: "ueberreden-zu",
    german: "überreden zu",
    english: "to persuade to",
    exampleDe: "Er hat mich dazu überredet, mitzukommen.",
    exampleEn: "He persuaded me to come along.",
  },
  {
    id: "kundschaft",
    german: "Kundschaft",
    english: "clientele / customers",
    exampleDe: "Unsere Kundschaft schätzt guten Service.",
    exampleEn: "Our clientele values good service.",
  },
  {
    id: "leidenschaft",
    german: "Leidenschaft",
    english: "passion",
    exampleDe: "Sie macht ihre Arbeit mit Leidenschaft.",
    exampleEn: "She does her work with passion.",
  },
  {
    id: "herausforderung",
    german: "Herausforderung",
    english: "challenge",
    exampleDe: "Das neue Projekt ist eine große Herausforderung.",
    exampleEn: "The new project is a big challenge.",
  },
  {
    id: "ueblich",
    german: "üblich",
    english: "usual / common",
    exampleDe: "In Deutschland ist es üblich, pünktlich zu sein.",
    exampleEn: "In Germany it is usual to be on time.",
  },
  {
    id: "im-zusammenhang-stehen-mit",
    german: "im Zusammenhang stehen mit",
    english: "to be related to / connected with",
    exampleDe: "Die Verzögerung steht im Zusammenhang mit dem Wetter.",
    exampleEn: "The delay is related to the weather.",
  },
  {
    id: "teamfaehig",
    german: "teamfähig",
    english: "able to work in a team",
    exampleDe: "Für diese Stelle müssen Sie teamfähig sein.",
    exampleEn: "For this position you must be able to work in a team.",
  },
  {
    id: "uebersichtlich",
    german: "übersichtlich",
    english: "clear / well laid out (for documents)",
    exampleDe: "Die Tabelle ist übersichtlich gestaltet.",
    exampleEn: "The table is clearly laid out.",
  },
  {
    id: "erstellen",
    german: "erstellen",
    english: "to create",
    exampleDe: "Ich erstelle gerade eine Präsentation.",
    exampleEn: "I am currently creating a presentation.",
  },
  {
    id: "einbringen-in",
    german: "einbringen in",
    english: "to bring into / to contribute to",
    exampleDe: "Sie bringt viele Ideen in das Team ein.",
    exampleEn: "She contributes many ideas to the team.",
  },
  {
    id: "die-einstellung-zu",
    german: "die Einstellung zu",
    english: "the attitude toward",
    exampleDe: "Seine Einstellung zur Arbeit hat sich verändert.",
    exampleEn: "His attitude toward work has changed.",
  },
  {
    id: "verhandlung",
    german: "Verhandlung",
    english: "negotiation",
    exampleDe: "Die Verhandlung mit dem Lieferanten war erfolgreich.",
    exampleEn: "The negotiation with the supplier was successful.",
  },
  {
    id: "einstellen",
    german: "einstellen",
    english: "to hire / to adjust / to set",
    exampleDe: "Wir wollen nächstes Jahr neue Mitarbeiter einstellen.",
    exampleEn: "We want to hire new employees next year.",
  },
  {
    id: "merken",
    german: "merken",
    english: "to notice / to remember",
    exampleDe: "Hast du den Unterschied gemerkt?",
    exampleEn: "Did you notice the difference?",
  },
  {
    id: "vorbereiten",
    german: "vorbereiten",
    english: "to prepare",
    exampleDe: "Ich muss mich auf das Meeting vorbereiten.",
    exampleEn: "I have to prepare for the meeting.",
  },
  {
    id: "gewinnbringend",
    german: "gewinnbringend",
    english: "profitable",
    exampleDe: "Das war eine gewinnbringende Investition.",
    exampleEn: "That was a profitable investment.",
  },
  {
    id: "zustaendig",
    german: "zuständig",
    english: "responsible / in charge",
    exampleDe: "Wer ist für diesen Bereich zuständig?",
    exampleEn: "Who is responsible for this area?",
  },
  {
    id: "gelegenheiten",
    german: "Gelegenheiten",
    english: "opportunities",
    exampleDe: "Nutze die Gelegenheiten, die sich dir bieten.",
    exampleEn: "Take the opportunities that come your way.",
  },
  {
    id: "schwaechen",
    german: "Schwächen",
    english: "weaknesses",
    exampleDe: "Jeder hat Stärken und Schwächen.",
    exampleEn: "Everyone has strengths and weaknesses.",
  },
  {
    id: "staerken",
    german: "Stärken",
    english: "strengths",
    exampleDe: "Kommunikation gehört zu meinen Stärken.",
    exampleEn: "Communication is one of my strengths.",
  },
  {
    id: "bewusst",
    german: "bewusst",
    english: "aware",
    exampleDe: "Ich bin mir der Risiken bewusst.",
    exampleEn: "I am aware of the risks.",
  },
  {
    id: "wie-tickst-du",
    german: "wie tickst du in dieser Situation?",
    english: "how do you operate / what's your take in this situation?",
    exampleDe: "Wie tickst du in dieser Situation?",
    exampleEn: "What's your take in this situation?",
  },

  // --- other 18 cards ---
  {
    id: "ausdruck",
    german: "Ausdruck",
    english: "expression",
    exampleDe: "Das ist ein nützlicher Ausdruck im Geschäftsleben.",
    exampleEn: "That is a useful expression in business life.",
  },
  {
    id: "vergleichen",
    german: "vergleichen",
    english: "to compare",
    exampleDe: "Vergleichen Sie die beiden Angebote.",
    exampleEn: "Compare the two offers.",
  },
  {
    id: "ausstattung",
    german: "Ausstattung",
    english: "equipment",
    exampleDe: "Die Ausstattung des Büros ist modern.",
    exampleEn: "The office equipment is modern.",
  },
  {
    id: "zu-bedienen",
    german: "zu bedienen",
    english: "to serve / to operate",
    exampleDe: "Das Gerät ist leicht zu bedienen.",
    exampleEn: "The device is easy to operate.",
  },
  {
    id: "bemuehung",
    german: "Bemühung",
    english: "effort",
    exampleDe: "Vielen Dank für Ihre Bemühung.",
    exampleEn: "Thank you very much for your effort.",
  },
  {
    id: "ausserdem",
    german: "Außerdem",
    english: "furthermore",
    exampleDe: "Außerdem müssen wir den Zeitplan prüfen.",
    exampleEn: "Furthermore, we have to check the schedule.",
  },
  {
    id: "einrichten",
    german: "einrichten",
    english: "to set up",
    exampleDe: "Können Sie mir ein neues Konto einrichten?",
    exampleEn: "Can you set up a new account for me?",
  },
  {
    id: "vorgesetzte",
    german: "Vorgesetzte",
    english: "superior / supervisor",
    exampleDe: "Ich spreche zuerst mit meiner Vorgesetzten.",
    exampleEn: "I will speak with my supervisor first.",
  },
  {
    id: "ob-und-wann",
    german: "ob und wann",
    english: "whether and when",
    exampleDe: "Es ist unklar, ob und wann die Lieferung kommt.",
    exampleEn: "It is unclear whether and when the delivery will arrive.",
  },
  {
    id: "reihenfolge",
    german: "Reihenfolge",
    english: "order / sequence",
    exampleDe: "Bitte beachten Sie die richtige Reihenfolge.",
    exampleEn: "Please note the correct sequence.",
  },
  {
    id: "erfassen",
    german: "erfassen",
    english: "to grasp / to capture / to record",
    exampleDe: "Wir müssen alle Daten sorgfältig erfassen.",
    exampleEn: "We have to record all data carefully.",
  },
  {
    id: "schicht",
    german: "Schicht",
    english: "shift / layer",
    exampleDe: "Heute arbeite ich in der Nachtschicht.",
    exampleEn: "Today I am working the night shift.",
  },
  {
    id: "stimmung",
    german: "Stimmung",
    english: "mood",
    exampleDe: "Die Stimmung im Team ist gut.",
    exampleEn: "The mood in the team is good.",
  },
  {
    id: "sich-umsehen",
    german: "sich umsehen",
    english: "to look around",
    exampleDe: "Ich möchte mich erst einmal umsehen.",
    exampleEn: "I would like to look around first.",
  },
  {
    id: "stattdessen",
    german: "Stattdessen",
    english: "instead",
    exampleDe: "Stattdessen nehmen wir den Zug.",
    exampleEn: "Instead, we will take the train.",
  },
  {
    id: "meistens",
    german: "Meistens",
    english: "mostly",
    exampleDe: "Meistens arbeite ich von zu Hause.",
    exampleEn: "Mostly I work from home.",
  },
  {
    id: "zusaetzlich",
    german: "Zusätzlich",
    english: "additionally",
    exampleDe: "Zusätzlich erhalten Sie eine Schulung.",
    exampleEn: "Additionally, you will receive training.",
  },
  {
    id: "am-meisten",
    german: "Am meisten",
    english: "the most",
    exampleDe: "Am meisten gefällt mir die klare Struktur.",
    exampleEn: "What I like the most is the clear structure.",
  },

  // --- 11 words added later ---
  {
    id: "sich-eignen",
    german: "sich eignen",
    english: "to be suited/qualified (for something)",
    exampleDe: "Sie eignet sich gut für diese Aufgabe.",
    exampleEn: "She is well suited for this task.",
  },
  {
    id: "vortrag",
    german: "Vortrag",
    english: "lecture, presentation",
    exampleDe: "Morgen halte ich einen Vortrag über Klimaschutz.",
    exampleEn: "Tomorrow I am giving a lecture on climate protection.",
  },
  {
    id: "sicherheit",
    german: "Sicherheit",
    english: "confidence",
    exampleDe: "Mit der Zeit wächst meine Sicherheit beim Sprechen.",
    exampleEn: "Over time, my confidence in speaking grows.",
  },
  {
    id: "beobachten",
    german: "beobachten",
    english: "to observe",
    exampleDe: "Ich beobachte die Vögel im Garten.",
    exampleEn: "I observe the birds in the garden.",
  },
  {
    id: "sich-fremdschaemen",
    german: "sich fremdschämen",
    english: "to feel secondhand embarrassment (cringe on someone else's behalf)",
    exampleDe: "Ich schäme mich fremd, wenn er so laut spricht.",
    exampleEn: "I feel secondhand embarrassment when he talks so loudly.",
  },
  {
    id: "sich-lohnen",
    german: "sich lohnen",
    english: "to be worth it",
    exampleDe: "Der Aufwand lohnt sich wirklich.",
    exampleEn: "The effort is really worth it.",
  },
  {
    id: "es-weit-bringen",
    german: "es weit bringen",
    english: "to achieve a lot, go far",
    exampleDe: "Mit Fleiß kannst du es weit bringen.",
    exampleEn: "With diligence, you can go far.",
  },
  {
    id: "es-kommt-auf-an",
    german: "Es kommt auf das Wetter an.",
    english: "It depends on the weather.",
    exampleDe: "Ob wir wandern gehen, kommt auf das Wetter an.",
    exampleEn: "Whether we go hiking depends on the weather.",
  },
  {
    id: "es-handelt-sich-um",
    german: "Es handelt sich um den Kundenservice.",
    english: "This is about/concerns customer service.",
    exampleDe: "Es handelt sich um den Kundenservice.",
    exampleEn: "This concerns customer service.",
  },
  {
    id: "ergaenzen",
    german: "ergänzen",
    english: "to add, supplement, complete",
    exampleDe: "Können Sie die Liste noch ergänzen?",
    exampleEn: "Can you still add to / complete the list?",
  },
  {
    id: "entfallen",
    german: "entfallen",
    english: "to be omitted, cancelled, or no longer apply",
    exampleDe: "Der Termin ist entfallen.",
    exampleEn: "The appointment has been cancelled.",
  },

  // --- notebook page 217 (not crossed out; skipped: über verfügen) ---
  {
    id: "ausreden",
    german: "ausreden",
    english: "to finish speaking / to make excuses",
    exampleDe: "Lass mich bitte ausreden.",
    exampleEn: "Please let me finish speaking.",
  },
  {
    id: "jmdn-stoeren",
    german: "jmdn. stören",
    english: "to disturb / interrupt someone",
    exampleDe: "Darf ich Sie kurz stören?",
    exampleEn: "May I disturb you briefly?",
  },
  {
    id: "betreffen",
    german: "betreffen",
    english: "to concern / affect",
    exampleDe: "Das betrifft alle Mitarbeiter.",
    exampleEn: "That concerns all employees.",
  },
  {
    id: "mir-ist-kalt",
    german: "Mir ist kalt.",
    english: "I'm cold.",
    exampleDe: "Kannst du das Fenster schließen? Mir ist kalt.",
    exampleEn: "Can you close the window? I'm cold.",
  },
  {
    id: "beurteilen",
    german: "beurteilen",
    english: "to assess / judge / evaluate",
    exampleDe: "Wie beurteilen Sie die Lage?",
    exampleEn: "How do you assess the situation?",
  },
  {
    id: "zusammenfassung-fazit",
    german: "Zusammenfassung / Fazit",
    english: "summary / conclusion",
    exampleDe: "Zum Schluss kommt eine kurze Zusammenfassung.",
    exampleEn: "At the end there is a short summary.",
  },
  {
    id: "schaetzen",
    german: "schätzen",
    english: "to value / appreciate / estimate",
    exampleDe: "Ich schätze Ihre Unterstützung sehr.",
    exampleEn: "I really appreciate your support.",
  },
  {
    id: "ich-setze-dich-in-cc",
    german: "ich setze dich in CC",
    english: "I'll put you in CC / I'll CC you",
    exampleDe: "Ich setze dich in CC, damit du informiert bleibst.",
    exampleEn: "I'll CC you so you stay informed.",
  },
  {
    id: "gestaltung",
    german: "Gestaltung",
    english: "design / layout / structuring",
    exampleDe: "Die Gestaltung der Präsentation ist klar und modern.",
    exampleEn: "The design of the presentation is clear and modern.",
  },
  {
    id: "abstimmen",
    german: "abstimmen",
    english: "to coordinate / align / vote (on)",
    exampleDe: "Wir müssen den Termin noch abstimmen.",
    exampleEn: "We still need to coordinate the appointment.",
  },
  {
    id: "zu-den-zeiten",
    german: "zu den Zeiten",
    english: "at those times / during those hours",
    exampleDe: "Zu den Zeiten bin ich meistens im Büro.",
    exampleEn: "At those times I am usually in the office.",
  },
  {
    id: "zeitnah",
    german: "zeitnah",
    english: "promptly / in a timely manner",
    exampleDe: "Bitte antworten Sie zeitnah auf die Anfrage.",
    exampleEn: "Please reply to the request promptly.",
  },
  {
    id: "inhaltlich",
    german: "inhaltlich",
    english: "in terms of content / substantively",
    exampleDe: "Inhaltlich ist der Bericht gut, aber zu lang.",
    exampleEn: "In terms of content the report is good, but too long.",
  },
  {
    id: "vorteile",
    german: "Vorteile",
    english: "advantages",
    exampleDe: "Die Vorteile dieses Ansatzes sind klar.",
    exampleEn: "The advantages of this approach are clear.",
  },
  {
    id: "nachteile",
    german: "Nachteile",
    english: "disadvantages",
    exampleDe: "Es gibt auch einige Nachteile.",
    exampleEn: "There are also some disadvantages.",
  },
  {
    id: "aufsicht",
    german: "Aufsicht",
    english: "supervision / oversight",
    exampleDe: "Die Kinder spielen unter Aufsicht.",
    exampleEn: "The children are playing under supervision.",
  },
  {
    id: "stattfinden",
    german: "stattfinden",
    english: "to take place",
    exampleDe: "Das Meeting findet morgen um 10 Uhr statt.",
    exampleEn: "The meeting takes place tomorrow at 10 o'clock.",
  },
  {
    id: "erreichen",
    german: "erreichen",
    english: "to reach / achieve",
    exampleDe: "Wie können wir dieses Ziel erreichen?",
    exampleEn: "How can we achieve this goal?",
  },
  {
    id: "verpflichtend",
    german: "verpflichtend",
    english: "mandatory / obligatory",
    exampleDe: "Die Teilnahme an der Schulung ist verpflichtend.",
    exampleEn: "Participation in the training is mandatory.",
  },
  {
    id: "nachvollziehbarkeit",
    german: "Nachvollziehbarkeit",
    english: "traceability / comprehensibility / auditability",
    exampleDe: "Für die Nachvollziehbarkeit dokumentieren wir jeden Schritt.",
    exampleEn: "For traceability, we document every step.",
  },
  {
    id: "zusammenfassen",
    german: "zusammenfassen",
    english: "to summarize",
    exampleDe: "Können Sie die wichtigsten Punkte zusammenfassen?",
    exampleEn: "Can you summarize the most important points?",
  },
  {
    id: "bezueglich",
    german: "bezüglich",
    english: "regarding / with regard to",
    exampleDe: "Bezüglich Ihres Antrags melden wir uns bald.",
    exampleEn: "Regarding your application, we will get back to you soon.",
  },
  {
    id: "gegenstand",
    german: "Gegenstand",
    english: "subject / object / matter (of discussion)",
    exampleDe: "Der Gegenstand der Besprechung ist der neue Zeitplan.",
    exampleEn: "The subject of the meeting is the new schedule.",
  },

  // --- notebook list (neidisch not niedrig; skip Reichweite) ---
  {
    id: "neidisch",
    german: "neidisch",
    english: "jealous",
    exampleDe: "Sei nicht neidisch auf seinen Erfolg.",
    exampleEn: "Don't be jealous of his success.",
  },
  {
    id: "was-habt-ihr-erfahren",
    german: "Was habt ihr erfahren?",
    english: "What did you find out / learn?",
    exampleDe: "Was habt ihr erfahren?",
    exampleEn: "What did you find out?",
  },
  {
    id: "sehenswuerdigkeit",
    german: "Sehenswürdigkeit",
    english: "tourist attraction / sight",
    exampleDe: "Der Kölner Dom ist eine bekannte Sehenswürdigkeit.",
    exampleEn: "Cologne Cathedral is a well-known tourist attraction.",
  },
  {
    id: "guenstig",
    german: "günstig",
    english: "inexpensive",
    exampleDe: "Das Hotel war überraschend günstig.",
    exampleEn: "The hotel was surprisingly inexpensive.",
  },
  {
    id: "irgendwann",
    german: "irgendwann",
    english: "sometime / eventually",
    exampleDe: "Irgendwann müssen wir uns entscheiden.",
    exampleEn: "Sometime we have to decide.",
  },
  {
    id: "aussuchen",
    german: "aussuchen",
    english: "to choose / pick out",
    exampleDe: "Such dir bitte ein Geschenk aus.",
    exampleEn: "Please pick out a gift.",
  },
  {
    id: "zuversichtlich",
    german: "zuversichtlich",
    english: "confident / optimistic",
    exampleDe: "Ich bin zuversichtlich, dass wir das schaffen.",
    exampleEn: "I am confident that we can do it.",
  },
  {
    id: "irgendwelche",
    german: "irgendwelche",
    english: "some / any (kind of)",
    exampleDe: "Hast du irgendwelche Fragen?",
    exampleEn: "Do you have any questions?",
  },
  {
    id: "innerhalb",
    german: "innerhalb",
    english: "within / inside",
    exampleDe: "Bitte antworten Sie innerhalb einer Woche.",
    exampleEn: "Please reply within one week.",
  },
  {
    id: "aufteilen",
    german: "aufteilen",
    english: "to divide / split up",
    exampleDe: "Wir teilen die Aufgaben unter uns auf.",
    exampleEn: "We split the tasks among ourselves.",
  },
  {
    id: "die-umsaetze",
    german: "die Umsätze",
    english: "sales / revenue (turnover)",
    exampleDe: "Die Umsätze sind dieses Jahr gestiegen.",
    exampleEn: "Sales have risen this year.",
  },
  {
    id: "die-gewinne",
    german: "die Gewinne",
    english: "profits",
    exampleDe: "Die Gewinne lagen über den Erwartungen.",
    exampleEn: "Profits were above expectations.",
  },
  {
    id: "vorstellen",
    german: "vorstellen",
    english: "to introduce / imagine / present",
    exampleDe: "Darf ich Ihnen meinen Kollegen vorstellen?",
    exampleEn: "May I introduce my colleague to you?",
  },
  {
    id: "geschaeft",
    german: "Geschäft",
    english: "business / store / deal",
    exampleDe: "Wir haben ein gutes Geschäft gemacht.",
    exampleEn: "We made a good deal.",
  },
  {
    id: "erwidern",
    german: "erwidern",
    english: "to reply / respond",
    exampleDe: "Sie erwiderte höflich auf die Kritik.",
    exampleEn: "She replied politely to the criticism.",
  },
  {
    id: "der-anlass",
    german: "der Anlass",
    english: "occasion / reason / cause",
    exampleDe: "Was war der Anlass für die Feier?",
    exampleEn: "What was the occasion for the celebration?",
  },
  {
    id: "verwoehnen",
    german: "verwöhnen",
    english: "to spoil / pamper",
    exampleDe: "Am Wochenende verwöhnen wir uns mit einem guten Essen.",
    exampleEn: "On the weekend we pamper ourselves with a nice meal.",
  },
  {
    id: "gewoehnen",
    german: "gewöhnen",
    english: "to get used to",
    exampleDe: "Ich muss mich an den neuen Zeitplan gewöhnen.",
    exampleEn: "I have to get used to the new schedule.",
  },
  {
    id: "jmdn-ankommen-lassen",
    german: "jmdn. ankommen lassen",
    english: "to let someone arrive / come through; also give someone a hard time (colloquial)",
    exampleDe: "Lass ihn erst einmal ankommen, bevor du Fragen stellst.",
    exampleEn: "Let him settle in first before you ask questions.",
  },
  {
    id: "es-laeuft-nicht-gut",
    german: "Es läuft nicht gut",
    english: "Things aren't going well",
    exampleDe: "Im Moment läuft es nicht gut im Projekt.",
    exampleEn: "Right now things aren't going well on the project.",
  },
  {
    id: "unbedingt",
    german: "unbedingt",
    english: "definitely / absolutely / by all means",
    exampleDe: "Du musst unbedingt Bescheid sagen.",
    exampleEn: "You absolutely have to let us know.",
  },
  {
    id: "uebrigens",
    german: "übrigens",
    english: "by the way",
    exampleDe: "Übrigens, hast du die E-Mail gelesen?",
    exampleEn: "By the way, did you read the email?",
  },
  {
    id: "auf-jeden-fall",
    german: "auf jeden Fall",
    english: "in any case / definitely",
    exampleDe: "Auf jeden Fall komme ich morgen.",
    exampleEn: "I am definitely coming tomorrow.",
  },
  {
    id: "aufpassen",
    german: "aufpassen",
    english: "to pay attention / watch out",
    exampleDe: "Pass auf der Straße gut auf.",
    exampleEn: "Watch out carefully on the street.",
  },
  {
    id: "ablehnend",
    german: "ablehnend",
    english: "rejecting / dismissive / negative (attitude)",
    exampleDe: "Seine Reaktion war eher ablehnend.",
    exampleEn: "His reaction was rather dismissive.",
  },
  {
    id: "binden",
    german: "binden",
    english: "to bind / tie / attach",
    exampleDe: "Bitte binde die Unterlagen zusammen.",
    exampleEn: "Please bind the documents together.",
  },
  {
    id: "jmdn-wecken",
    german: "jmdn. wecken",
    english: "to wake someone up",
    exampleDe: "Kannst du mich um 7 Uhr wecken?",
    exampleEn: "Can you wake me up at 7 o'clock?",
  },
  {
    id: "ansprechen",
    german: "ansprechen",
    english: "to address / speak to / bring up",
    exampleDe: "Ich möchte das Thema im Meeting ansprechen.",
    exampleEn: "I want to bring up the topic in the meeting.",
  },

  // --- notebook list (skip #8 behindern, #15 schnorren; ich vermute without Vermutung) ---
  {
    id: "etw-warten",
    german: "etw. warten",
    english: "to wait for something",
    exampleDe: "Ich warte auf deine Antwort.",
    exampleEn: "I am waiting for your answer.",
  },
  {
    id: "jmdn-etw-vertreten",
    german: "jmdn./etw. vertreten",
    english: "to represent someone/something",
    exampleDe: "Sie vertritt die Firma bei der Messe.",
    exampleEn: "She represents the company at the trade fair.",
  },
  {
    id: "essensgerueche",
    german: "Essensgerüche",
    english: "food smells / cooking odors",
    exampleDe: "Im Flur riecht man starke Essensgerüche.",
    exampleEn: "In the hallway you can smell strong food odors.",
  },
  {
    id: "belaestigung",
    german: "Belästigung",
    english: "harassment / nuisance",
    exampleDe: "Belästigung am Arbeitsplatz wird nicht akzeptiert.",
    exampleEn: "Harassment at the workplace is not accepted.",
  },
  {
    id: "rechnen",
    german: "rechnen",
    english: "to calculate / count (on)",
    exampleDe: "Wir rechnen mit einer Verzögerung.",
    exampleEn: "We are counting on a delay. / We expect a delay.",
  },
  {
    id: "betreiben",
    german: "betreiben",
    english: "to run / operate (a business)",
    exampleDe: "Er betreibt ein kleines Café in der Stadt.",
    exampleEn: "He runs a small café in the city.",
  },
  {
    id: "in-betrieb",
    german: "in Betrieb",
    english: "in operation / up and running",
    exampleDe: "Die neue Anlage ist seit Montag in Betrieb.",
    exampleEn: "The new facility has been in operation since Monday.",
  },
  {
    id: "vor-allem",
    german: "vor allem",
    english: "above all / especially",
    exampleDe: "Vor allem brauchen wir mehr Zeit.",
    exampleEn: "Above all, we need more time.",
  },
  {
    id: "vielfalt",
    german: "Vielfalt",
    english: "diversity / variety",
    exampleDe: "Die Vielfalt im Team ist eine große Stärke.",
    exampleEn: "The diversity in the team is a big strength.",
  },
  {
    id: "geniessen",
    german: "genießen",
    english: "to enjoy",
    exampleDe: "Genieß den Abend mit deinen Freunden.",
    exampleEn: "Enjoy the evening with your friends.",
  },
  {
    id: "wir-schlossen-ab",
    german: "wir schlossen ab",
    english: "we concluded / closed / finalized",
    exampleDe: "Gestern schlossen wir das Projekt ab.",
    exampleEn: "Yesterday we finalized the project.",
  },
  {
    id: "wir-machen-weiter",
    german: "wir machen weiter",
    english: "we continue / we'll keep going",
    exampleDe: "Trotz der Probleme machen wir weiter.",
    exampleEn: "Despite the problems, we keep going.",
  },
  {
    id: "wegen",
    german: "wegen",
    english: "because of / due to",
    exampleDe: "Wegen des Regens fällt der Termin aus.",
    exampleEn: "Because of the rain, the appointment is cancelled.",
  },
  {
    id: "vorsichtig",
    german: "vorsichtig",
    english: "careful / cautious",
    exampleDe: "Sei bitte vorsichtig auf dem Weg.",
    exampleEn: "Please be careful on the way.",
  },
  {
    id: "gleichberechtigt",
    german: "gleichberechtigt",
    english: "equal / with equal rights",
    exampleDe: "Sie arbeiten als gleichberechtigte Partner zusammen.",
    exampleEn: "They work together as equal partners.",
  },
  {
    id: "einbeziehen-in",
    german: "einbeziehen in",
    english: "to include in / involve in",
    exampleDe: "Bitte beziehen Sie alle Kollegen in die Planung ein.",
    exampleEn: "Please include all colleagues in the planning.",
  },
  {
    id: "es-scheint",
    german: "Es scheint",
    english: "It seems",
    exampleDe: "Es scheint, als ob wir uns verspätet haben.",
    exampleEn: "It seems as if we are late.",
  },
  {
    id: "ich-vermute",
    german: "ich vermute",
    english: "I assume / I suspect",
    exampleDe: "Ich vermute, dass er später kommt.",
    exampleEn: "I assume that he will come later.",
  },
  {
    id: "gesetzt",
    german: "gesetzt",
    english: "composed / settled / established",
    exampleDe: "Trotz des Stresses blieb sie sehr gesetzt.",
    exampleEn: "Despite the stress, she remained very composed.",
  },
  {
    id: "loesungsorientiert",
    german: "lösungsorientiert",
    english: "solution-oriented",
    exampleDe: "Wir brauchen eine lösungsorientierte Haltung.",
    exampleEn: "We need a solution-oriented attitude.",
  },
  {
    id: "anpassungsfaehig",
    german: "anpassungsfähig",
    english: "adaptable",
    exampleDe: "In diesem Job muss man anpassungsfähig sein.",
    exampleEn: "In this job you have to be adaptable.",
  },
  {
    id: "zuverlaessig",
    german: "zuverlässig",
    english: "reliable",
    exampleDe: "Er ist ein zuverlässiger Kollege.",
    exampleEn: "He is a reliable colleague.",
  },
  {
    id: "belastbar",
    german: "belastbar",
    english: "resilient / able to handle pressure",
    exampleDe: "Unter Druck bleibt sie belastbar.",
    exampleEn: "Under pressure she remains resilient.",
  },
  {
    id: "tatkraeftig",
    german: "tatkräftig",
    english: "energetic / proactive / hands-on",
    exampleDe: "Wir suchen tatkräftige Unterstützung.",
    exampleEn: "We are looking for hands-on support.",
  },
  {
    id: "vorzug",
    german: "Vorzug",
    english: "preference / preferential advantage",
    exampleDe: "Ich gebe dem ersten Vorschlag den Vorzug.",
    exampleEn: "I give preference to the first proposal.",
  },
  {
    id: "neugierig",
    german: "neugierig",
    english: "curious",
    exampleDe: "Kinder sind von Natur aus neugierig.",
    exampleEn: "Children are naturally curious.",
  },
  {
    id: "auswaehlen",
    german: "auswählen",
    english: "to select / choose",
    exampleDe: "Bitte wählen Sie eine Option aus.",
    exampleEn: "Please select an option.",
  },
  {
    id: "bewerten",
    german: "bewerten",
    english: "to evaluate / rate",
    exampleDe: "Können Sie das Ergebnis kurz bewerten?",
    exampleEn: "Can you briefly evaluate the result?",
  },
  {
    id: "verbringen",
    german: "verbringen",
    english: "to spend (time)",
    exampleDe: "Wir verbringen das Wochenende am See.",
    exampleEn: "We are spending the weekend at the lake.",
  },

  // --- notebook list (skip Durchwahl #8 and Voraussetzung #23; vermeiden as own word; removed duzen/Siezen) ---
  {
    id: "teamgeist",
    german: "Teamgeist",
    english: "team spirit",
    exampleDe: "Guter Teamgeist macht die Arbeit leichter.",
    exampleEn: "Good team spirit makes the work easier.",
  },
  {
    id: "gemeinsam",
    german: "gemeinsam",
    english: "together / jointly",
    exampleDe: "Wir lösen das Problem gemeinsam.",
    exampleEn: "We solve the problem together.",
  },
  {
    id: "worum-geht-es",
    german: "Worum geht es?",
    english: "What is it about?",
    exampleDe: "Worum geht es in diesem Meeting?",
    exampleEn: "What is this meeting about?",
  },
  {
    id: "ein-angebot-unterbreiten",
    german: "ein Angebot unterbreiten",
    english: "to make / submit an offer",
    exampleDe: "Darf ich Ihnen ein Angebot unterbreiten?",
    exampleEn: "May I make you an offer?",
  },
  {
    id: "zur-verfuegung",
    german: "zur Verfügung",
    english: "available / at one's disposal",
    exampleDe: "Die Unterlagen stehen Ihnen zur Verfügung.",
    exampleEn: "The documents are at your disposal.",
  },
  {
    id: "festhalten",
    german: "festhalten",
    english: "to hold on to / record / note down",
    exampleDe: "Bitte halten Sie die wichtigsten Punkte fest.",
    exampleEn: "Please note down the most important points.",
  },
  {
    id: "verbleiben",
    german: "verbleiben",
    english: "to remain / to be left",
    exampleDe: "Es verbleiben noch zwei offene Fragen.",
    exampleEn: "Two open questions remain.",
  },
  {
    id: "ausrichten",
    german: "ausrichten",
    english: "to arrange / pass on (a message) / align",
    exampleDe: "Kannst du ihm bitte etwas ausrichten?",
    exampleEn: "Can you please pass a message on to him?",
  },
  {
    id: "vergewissern",
    german: "vergewissern",
    english: "to make sure / verify",
    exampleDe: "Ich möchte mich vergewissern, dass alles klar ist.",
    exampleEn: "I want to make sure that everything is clear.",
  },
  {
    id: "machen-wir-weiter",
    german: "machen wir weiter",
    english: "let's continue",
    exampleDe: "Gut, machen wir weiter mit dem nächsten Punkt.",
    exampleEn: "Good, let's continue with the next point.",
  },
  {
    id: "voraussetzungen",
    german: "Voraussetzungen",
    english: "requirements / prerequisites",
    exampleDe: "Welche Voraussetzungen braucht man für den Kurs?",
    exampleEn: "What requirements are needed for the course?",
  },
  {
    id: "missverstaendnisse",
    german: "Missverständnisse",
    english: "misunderstandings",
    exampleDe: "Kleine Missverständnisse können große Probleme verursachen.",
    exampleEn: "Small misunderstandings can cause big problems.",
  },
  {
    id: "vermeiden",
    german: "vermeiden",
    english: "to avoid",
    exampleDe: "Wir sollten Missverständnisse möglichst vermeiden.",
    exampleEn: "We should avoid misunderstandings as much as possible.",
  },
  {
    id: "hinterlassen",
    german: "hinterlassen",
    english: "to leave behind / leave (a message)",
    exampleDe: "Können Sie bitte eine Nachricht hinterlassen?",
    exampleEn: "Can you please leave a message?",
  },
  {
    id: "verabschieden",
    german: "verabschieden",
    english: "to say goodbye / adopt (a law/resolution)",
    exampleDe: "Wir verabschieden uns am Bahnhof.",
    exampleEn: "We say goodbye at the train station.",
  },
  {
    id: "du-bist-dran",
    german: "Du bist dran",
    english: "It's your turn",
    exampleDe: "Du bist dran, die Präsentation zu halten.",
    exampleEn: "It's your turn to give the presentation.",
  },
  {
    id: "deutlich",
    german: "deutlich",
    english: "clear / clearly",
    exampleDe: "Bitte sprechen Sie deutlich und langsam.",
    exampleEn: "Please speak clearly and slowly.",
  },
  {
    id: "anschein",
    german: "Anschein",
    english: "appearance / impression",
    exampleDe: "Dem Anschein nach ist alles in Ordnung.",
    exampleEn: "By all appearances, everything is fine.",
  },
  {
    id: "eigenschaften",
    german: "Eigenschaften",
    english: "qualities / characteristics / properties",
    exampleDe: "Welche Eigenschaften sind für diesen Job wichtig?",
    exampleEn: "Which qualities are important for this job?",
  },
  {
    id: "aufraeumen",
    german: "aufräumen",
    english: "to tidy up / clean up",
    exampleDe: "Nach dem Meeting räumen wir den Raum auf.",
    exampleEn: "After the meeting we tidy up the room.",
  },
  {
    id: "ich-habe-vor",
    german: "ich habe vor",
    english: "I intend / I'm planning to",
    exampleDe: "Ich habe vor, nächstes Jahr nach Berlin zu ziehen.",
    exampleEn: "I intend to move to Berlin next year.",
  },
  {
    id: "staatsangehoerigkeit",
    german: "Staatsangehörigkeit",
    english: "nationality / citizenship",
    exampleDe: "Welche Staatsangehörigkeit haben Sie?",
    exampleEn: "What nationality do you have?",
  },
  {
    id: "aufwachen",
    german: "aufwachen",
    english: "to wake up",
    exampleDe: "Ich wache jeden Tag um sechs Uhr auf.",
    exampleEn: "I wake up at six o'clock every day.",
  },
  {
    id: "ich-bin-es-nicht-gewohnt",
    german: "ich bin es nicht gewohnt",
    english: "I'm not used to it",
    exampleDe: "Ich bin es nicht gewohnt, so früh aufzustehen.",
    exampleEn: "I'm not used to getting up so early.",
  },
  {
    id: "absolvieren",
    german: "absolvieren",
    english: "to complete / graduate from / get through",
    exampleDe: "Sie hat ihr Studium erfolgreich absolviert.",
    exampleEn: "She successfully completed her studies.",
  },
  {
    id: "durchlaufen",
    german: "durchlaufen",
    english: "to go through / pass through",
    exampleDe: "Jeder Bewerber muss denselben Prozess durchlaufen.",
    exampleEn: "Every applicant has to go through the same process.",
  },
  {
    id: "annehmen",
    german: "annehmen",
    english: "to accept / assume",
    exampleDe: "Ich nehme an, dass er später kommt.",
    exampleEn: "I assume that he will come later.",
  },
  {
    id: "abwickeln",
    german: "abwickeln",
    english: "to process / handle / wind up",
    exampleDe: "Wir wickeln die Bestellung heute noch ab.",
    exampleEn: "We will process the order today.",
  },
  {
    id: "ausfuehren",
    german: "ausführen",
    english: "to carry out / execute / export",
    exampleDe: "Bitte führen Sie den Plan genau aus.",
    exampleEn: "Please carry out the plan exactly.",
  },
  {
    id: "sachlich",
    german: "sachlich",
    english: "factual / objective / matter-of-fact",
    exampleDe: "Bleiben wir bitte sachlich in der Diskussion.",
    exampleEn: "Let's please stay factual in the discussion.",
  },
  {
    id: "verhalten",
    german: "verhalten",
    english: "behavior / to behave",
    exampleDe: "Sein Verhalten war sehr professionell.",
    exampleEn: "His behavior was very professional.",
  },
  {
    id: "erledigen",
    german: "erledigen",
    english: "to take care of / get done",
    exampleDe: "Kannst du das heute noch erledigen?",
    exampleEn: "Can you take care of that today?",
  },
  {
    id: "feststellen",
    german: "feststellen",
    english: "to determine / establish / notice",
    exampleDe: "Wir haben festgestellt, dass ein Fehler vorliegt.",
    exampleEn: "We have determined that there is an error.",
  },
  {
    id: "erlaeutern",
    german: "erläutern",
    english: "to explain / clarify",
    exampleDe: "Können Sie den Vorschlag bitte näher erläutern?",
    exampleEn: "Can you please explain the proposal in more detail?",
  },
  {
    id: "angemessen",
    german: "angemessen",
    english: "appropriate / reasonable",
    exampleDe: "Das ist eine angemessene Lösung.",
    exampleEn: "That is an appropriate solution.",
  },
  {
    id: "langfristig",
    german: "langfristig",
    english: "long-term",
    exampleDe: "Wir denken langfristig über die Strategie nach.",
    exampleEn: "We are thinking long-term about the strategy.",
  },
  {
    id: "giessen",
    german: "gießen",
    english: "to pour / to water (plants)",
    exampleDe: "Vergiss nicht, die Pflanzen zu gießen.",
    exampleEn: "Don't forget to water the plants.",
  },
  {
    id: "dadurch",
    german: "dadurch",
    english: "thereby / as a result / by that",
    exampleDe: "Dadurch sparen wir viel Zeit.",
    exampleEn: "As a result, we save a lot of time.",
  },
  {
    id: "fordern",
    german: "fordern",
    english: "to demand / require",
    exampleDe: "Die Kunden fordern bessere Qualität.",
    exampleEn: "The customers demand better quality.",
  },
  {
    id: "besetzen",
    german: "besetzen",
    english: "to occupy / fill (a position)",
    exampleDe: "Die Stelle wird bald neu besetzt.",
    exampleEn: "The position will soon be filled.",
  },
  {
    id: "abfahren",
    german: "abfahren",
    english: "to depart / leave",
    exampleDe: "Der Zug fährt um 9 Uhr ab.",
    exampleEn: "The train departs at 9 o'clock.",
  },
  {
    id: "eventuell",
    german: "eventuell",
    english: "possibly / maybe",
    exampleDe: "Eventuell komme ich etwas später.",
    exampleEn: "I may possibly come a bit later.",
  },
  {
    id: "wozu-lernen-sie-deutsch",
    german: "Wozu lernen Sie Deutsch?",
    english: "Why / for what purpose are you learning German?",
    exampleDe: "Wozu lernen Sie Deutsch?",
    exampleEn: "For what purpose are you learning German?",
  },
  {
    id: "ich-gehe-davon-aus",
    german: "ich gehe davon aus",
    english: "I assume / I'm proceeding on the assumption that",
    exampleDe: "Ich gehe davon aus, dass wir uns einig sind.",
    exampleEn: "I assume that we are in agreement.",
  },
  {
    id: "die-wiedergutmachung",
    german: "die Wiedergutmachung",
    english: "compensation / reparation / making amends",
    exampleDe: "Er hat Wiedergutmachung für den Fehler angeboten.",
    exampleEn: "He offered compensation for the mistake.",
  },
];
