/**
 * Seed vocabulary for the German flashcard app.
 * Progress (status / lastReviewedAt) is stored separately in localStorage.
 * Custom/imported words are stored under wortkarte.custom.v1.
 */
window.SEED_WORDS = [
  // --- 54 from notebook import ---
  {
    id: "schlussendlich",
    german: "schlussendlich",
    english: "finally / ultimately",
    exampleDe: "Schlussendlich haben wir uns für den günstigeren Plan entschieden.",
    exampleEn: "Ultimately, we decided on the cheaper plan.",
  },
  {
    id: "endlich",
    german: "endlich",
    english: "finally",
    exampleDe: "Endlich ist das Projekt fertig.",
    exampleEn: "The project is finally finished.",
  },
  {
    id: "absicht",
    german: "Absicht",
    english: "intention",
    exampleDe: "Das war nicht meine Absicht.",
    exampleEn: "That was not my intention.",
  },
  {
    id: "ursachen",
    german: "Ursachen",
    english: "causes",
    exampleDe: "Wir müssen die Ursachen des Problems finden.",
    exampleEn: "We have to find the causes of the problem.",
  },
  {
    id: "anbieten",
    german: "anbieten",
    english: "to offer",
    exampleDe: "Darf ich Ihnen etwas zu trinken anbieten?",
    exampleEn: "May I offer you something to drink?",
  },
  {
    id: "faehigkeiten",
    german: "Fähigkeiten",
    english: "skills / abilities",
    exampleDe: "Ihre sprachlichen Fähigkeiten sind sehr gut.",
    exampleEn: "Your language skills are very good.",
  },
  {
    id: "taetigkeiten",
    german: "Tätigkeiten",
    english: "activities",
    exampleDe: "Zu meinen Tätigkeiten gehört auch die Kundenberatung.",
    exampleEn: "My activities also include customer consulting.",
  },
  {
    id: "rat-und-tat",
    german: "Rat und Tat",
    english: "tips and tricks / advice and practical help",
    exampleDe: "Er steht mir mit Rat und Tat zur Seite.",
    exampleEn: "He supports me with advice and practical help.",
  },
  {
    id: "einstellung",
    german: "Einstellung",
    english: "attitude (internal)",
    exampleDe: "Eine positive Einstellung hilft in schwierigen Situationen.",
    exampleEn: "A positive attitude helps in difficult situations.",
  },
  {
    id: "ausstrahlung",
    german: "Ausstrahlung",
    english: "presence / aura (external)",
    exampleDe: "Sie hat eine ruhige Ausstrahlung.",
    exampleEn: "She has a calm presence.",
  },
  {
    id: "allgemein",
    german: "allgemein",
    english: "general / generally",
    exampleDe: "Allgemein bin ich mit dem Ergebnis zufrieden.",
    exampleEn: "Generally, I am satisfied with the result.",
  },
  {
    id: "genauigkeit",
    german: "Genauigkeit",
    english: "accuracy",
    exampleDe: "Bei diesem Bericht kommt es auf Genauigkeit an.",
    exampleEn: "Accuracy matters in this report.",
  },
  {
    id: "ausfuehrlich",
    german: "ausführlich",
    english: "detailed / thorough",
    exampleDe: "Bitte beschreiben Sie das Problem ausführlich.",
    exampleEn: "Please describe the problem in detail.",
  },
  {
    id: "zufaellig",
    german: "zufällig",
    english: "by chance / accidental",
    exampleDe: "Ich habe sie zufällig im Zug getroffen.",
    exampleEn: "I met her by chance on the train.",
  },
  {
    id: "gestalten",
    german: "gestalten",
    english: "to shape / to design",
    exampleDe: "Wir wollen den Prozess neu gestalten.",
    exampleEn: "We want to redesign the process.",
  },
  {
    id: "wachsen",
    german: "wachsen",
    english: "to grow",
    exampleDe: "Das Unternehmen wächst jedes Jahr.",
    exampleEn: "The company grows every year.",
  },
  {
    id: "verantwortung",
    german: "Verantwortung",
    english: "responsibility",
    exampleDe: "Ich übernehme die Verantwortung für dieses Projekt.",
    exampleEn: "I take responsibility for this project.",
  },
  {
    id: "beitragen",
    german: "beitragen",
    english: "to contribute",
    exampleDe: "Jeder kann zum Erfolg beitragen.",
    exampleEn: "Everyone can contribute to success.",
  },
  {
    id: "beeinflussen",
    german: "beeinflussen",
    english: "to influence",
    exampleDe: "Werbung kann Kaufentscheidungen beeinflussen.",
    exampleEn: "Advertising can influence purchasing decisions.",
  },
  {
    id: "entwickeln",
    german: "entwickeln",
    english: "to develop",
    exampleDe: "Wir entwickeln eine neue Strategie.",
    exampleEn: "We are developing a new strategy.",
  },
  {
    id: "uebernehmen",
    german: "übernehmen",
    english: "to take on / to take over",
    exampleDe: "Kannst du diese Aufgabe übernehmen?",
    exampleEn: "Can you take on this task?",
  },
  {
    id: "steuerung",
    german: "Steuerung",
    english: "control / steering",
    exampleDe: "Die Steuerung des Projekts liegt bei der Projektleitung.",
    exampleEn: "Control of the project lies with the project lead.",
  },
  {
    id: "umsetzung",
    german: "Umsetzung",
    english: "implementation",
    exampleDe: "Die Umsetzung des Plans beginnt nächste Woche.",
    exampleEn: "Implementation of the plan begins next week.",
  },
  {
    id: "entwerfen",
    german: "entwerfen",
    english: "to design / to draft",
    exampleDe: "Sie entwirft ein neues Logo für die Firma.",
    exampleEn: "She is designing a new logo for the company.",
  },
  {
    id: "umfeld",
    german: "Umfeld",
    english: "environment / surroundings",
    exampleDe: "Ein ruhiges Umfeld hilft beim Lernen.",
    exampleEn: "A quiet environment helps with learning.",
  },
  {
    id: "verlaessliche",
    german: "verlässliche",
    english: "reliable",
    exampleDe: "Wir brauchen verlässliche Informationen.",
    exampleEn: "We need reliable information.",
  },
  {
    id: "bestehen",
    german: "bestehen",
    english: "to exist / to pass / to consist",
    exampleDe: "Die Prüfung besteht aus drei Teilen.",
    exampleEn: "The exam consists of three parts.",
  },
  {
    id: "detailliert",
    german: "detailliert",
    english: "detailed",
    exampleDe: "Bitte senden Sie mir eine detaillierte Übersicht.",
    exampleEn: "Please send me a detailed overview.",
  },
  {
    id: "unterstuetzen-bei",
    german: "unterstützen bei",
    english: "to support with",
    exampleDe: "Ich unterstütze dich bei der Vorbereitung.",
    exampleEn: "I support you with the preparation.",
  },
  {
    id: "selbststaendigkeit",
    german: "Selbständigkeit",
    english: "independence",
    exampleDe: "Selbständigkeit ist in diesem Beruf sehr wichtig.",
    exampleEn: "Independence is very important in this job.",
  },
  {
    id: "noetig",
    german: "nötig",
    english: "necessary",
    exampleDe: "Ist das wirklich nötig?",
    exampleEn: "Is that really necessary?",
  },
  {
    id: "dauer",
    german: "Dauer",
    english: "duration",
    exampleDe: "Die Dauer des Kurses beträgt sechs Wochen.",
    exampleEn: "The duration of the course is six weeks.",
  },
  {
    id: "ueberreden-zu",
    german: "überreden zu",
    english: "to persuade to",
    exampleDe: "Er hat mich dazu überredet, mitzukommen.",
    exampleEn: "He persuaded me to come along.",
  },
  {
    id: "kundschaft",
    german: "Kundschaft",
    english: "clientele / customers",
    exampleDe: "Unsere Kundschaft schätzt guten Service.",
    exampleEn: "Our clientele values good service.",
  },
  {
    id: "leidenschaft",
    german: "Leidenschaft",
    english: "passion",
    exampleDe: "Sie macht ihre Arbeit mit Leidenschaft.",
    exampleEn: "She does her work with passion.",
  },
  {
    id: "herausforderung",
    german: "Herausforderung",
    english: "challenge",
    exampleDe: "Das neue Projekt ist eine große Herausforderung.",
    exampleEn: "The new project is a big challenge.",
  },
  {
    id: "ueblich",
    german: "üblich",
    english: "usual / common",
    exampleDe: "In Deutschland ist es üblich, pünktlich zu sein.",
    exampleEn: "In Germany it is usual to be on time.",
  },
  {
    id: "im-zusammenhang-stehen-mit",
    german: "im Zusammenhang stehen mit",
    english: "to be related to / connected with",
    exampleDe: "Die Verzögerung steht im Zusammenhang mit dem Wetter.",
    exampleEn: "The delay is related to the weather.",
  },
  {
    id: "teamfaehig",
    german: "teamfähig",
    english: "able to work in a team",
    exampleDe: "Für diese Stelle müssen Sie teamfähig sein.",
    exampleEn: "For this position you must be able to work in a team.",
  },
  {
    id: "uebersichtlich",
    german: "übersichtlich",
    english: "clear / well laid out (for documents)",
    exampleDe: "Die Tabelle ist übersichtlich gestaltet.",
    exampleEn: "The table is clearly laid out.",
  },
  {
    id: "erstellen",
    german: "erstellen",
    english: "to create",
    exampleDe: "Ich erstelle gerade eine Präsentation.",
    exampleEn: "I am currently creating a presentation.",
  },
  {
    id: "einbringen-in",
    german: "einbringen in",
    english: "to bring into / to contribute to",
    exampleDe: "Sie bringt viele Ideen in das Team ein.",
    exampleEn: "She contributes many ideas to the team.",
  },
  {
    id: "die-einstellung-zu",
    german: "die Einstellung zu",
    english: "the attitude toward",
    exampleDe: "Seine Einstellung zur Arbeit hat sich verändert.",
    exampleEn: "His attitude toward work has changed.",
  },
  {
    id: "verhandlung",
    german: "Verhandlung",
    english: "negotiation",
    exampleDe: "Die Verhandlung mit dem Lieferanten war erfolgreich.",
    exampleEn: "The negotiation with the supplier was successful.",
  },
  {
    id: "einstellen",
    german: "einstellen",
    english: "to hire / to adjust / to set",
    exampleDe: "Wir wollen nächstes Jahr neue Mitarbeiter einstellen.",
    exampleEn: "We want to hire new employees next year.",
  },
  {
    id: "merken",
    german: "merken",
    english: "to notice / to remember",
    exampleDe: "Hast du den Unterschied gemerkt?",
    exampleEn: "Did you notice the difference?",
  },
  {
    id: "vorbereiten",
    german: "vorbereiten",
    english: "to prepare",
    exampleDe: "Ich muss mich auf das Meeting vorbereiten.",
    exampleEn: "I have to prepare for the meeting.",
  },
  {
    id: "gewinnbringend",
    german: "gewinnbringend",
    english: "profitable",
    exampleDe: "Das war eine gewinnbringende Investition.",
    exampleEn: "That was a profitable investment.",
  },
  {
    id: "zustaendig",
    german: "zuständig",
    english: "responsible / in charge",
    exampleDe: "Wer ist für diesen Bereich zuständig?",
    exampleEn: "Who is responsible for this area?",
  },
  {
    id: "gelegenheiten",
    german: "Gelegenheiten",
    english: "opportunities",
    exampleDe: "Nutze die Gelegenheiten, die sich dir bieten.",
    exampleEn: "Take the opportunities that come your way.",
  },
  {
    id: "schwaechen",
    german: "Schwächen",
    english: "weaknesses",
    exampleDe: "Jeder hat Stärken und Schwächen.",
    exampleEn: "Everyone has strengths and weaknesses.",
  },
  {
    id: "staerken",
    german: "Stärken",
    english: "strengths",
    exampleDe: "Kommunikation gehört zu meinen Stärken.",
    exampleEn: "Communication is one of my strengths.",
  },
  {
    id: "bewusst",
    german: "bewusst",
    english: "aware",
    exampleDe: "Ich bin mir der Risiken bewusst.",
    exampleEn: "I am aware of the risks.",
  },
  {
    id: "wie-tickst-du",
    german: "wie tickst du in dieser Situation?",
    english: "how do you operate / what's your take in this situation?",
    exampleDe: "Wie tickst du in dieser Situation?",
    exampleEn: "What's your take in this situation?",
  },

  // --- other 18 cards ---
  {
    id: "ausdruck",
    german: "Ausdruck",
    english: "expression",
    exampleDe: "Das ist ein nützlicher Ausdruck im Geschäftsleben.",
    exampleEn: "That is a useful expression in business life.",
  },
  {
    id: "vergleichen",
    german: "vergleichen",
    english: "to compare",
    exampleDe: "Vergleichen Sie die beiden Angebote.",
    exampleEn: "Compare the two offers.",
  },
  {
    id: "ausstattung",
    german: "Ausstattung",
    english: "equipment",
    exampleDe: "Die Ausstattung des Büros ist modern.",
    exampleEn: "The office equipment is modern.",
  },
  {
    id: "zu-bedienen",
    german: "zu bedienen",
    english: "to serve / to operate",
    exampleDe: "Das Gerät ist leicht zu bedienen.",
    exampleEn: "The device is easy to operate.",
  },
  {
    id: "bemuehung",
    german: "Bemühung",
    english: "effort",
    exampleDe: "Vielen Dank für Ihre Bemühung.",
    exampleEn: "Thank you very much for your effort.",
  },
  {
    id: "ausserdem",
    german: "Außerdem",
    english: "furthermore",
    exampleDe: "Außerdem müssen wir den Zeitplan prüfen.",
    exampleEn: "Furthermore, we have to check the schedule.",
  },
  {
    id: "einrichten",
    german: "einrichten",
    english: "to set up",
    exampleDe: "Können Sie mir ein neues Konto einrichten?",
    exampleEn: "Can you set up a new account for me?",
  },
  {
    id: "vorgesetzte",
    german: "Vorgesetzte",
    english: "superior / supervisor",
    exampleDe: "Ich spreche zuerst mit meiner Vorgesetzten.",
    exampleEn: "I will speak with my supervisor first.",
  },
  {
    id: "ob-und-wann",
    german: "ob und wann",
    english: "whether and when",
    exampleDe: "Es ist unklar, ob und wann die Lieferung kommt.",
    exampleEn: "It is unclear whether and when the delivery will arrive.",
  },
  {
    id: "reihenfolge",
    german: "Reihenfolge",
    english: "order / sequence",
    exampleDe: "Bitte beachten Sie die richtige Reihenfolge.",
    exampleEn: "Please note the correct sequence.",
  },
  {
    id: "erfassen",
    german: "erfassen",
    english: "to grasp / to capture / to record",
    exampleDe: "Wir müssen alle Daten sorgfältig erfassen.",
    exampleEn: "We have to record all data carefully.",
  },
  {
    id: "schicht",
    german: "Schicht",
    english: "shift / layer",
    exampleDe: "Heute arbeite ich in der Nachtschicht.",
    exampleEn: "Today I am working the night shift.",
  },
  {
    id: "stimmung",
    german: "Stimmung",
    english: "mood",
    exampleDe: "Die Stimmung im Team ist gut.",
    exampleEn: "The mood in the team is good.",
  },
  {
    id: "sich-umsehen",
    german: "sich umsehen",
    english: "to look around",
    exampleDe: "Ich möchte mich erst einmal umsehen.",
    exampleEn: "I would like to look around first.",
  },
  {
    id: "stattdessen",
    german: "Stattdessen",
    english: "instead",
    exampleDe: "Stattdessen nehmen wir den Zug.",
    exampleEn: "Instead, we will take the train.",
  },
  {
    id: "meistens",
    german: "Meistens",
    english: "mostly",
    exampleDe: "Meistens arbeite ich von zu Hause.",
    exampleEn: "Mostly I work from home.",
  },
  {
    id: "zusaetzlich",
    german: "Zusätzlich",
    english: "additionally",
    exampleDe: "Zusätzlich erhalten Sie eine Schulung.",
    exampleEn: "Additionally, you will receive training.",
  },
  {
    id: "am-meisten",
    german: "Am meisten",
    english: "the most",
    exampleDe: "Am meisten gefällt mir die klare Struktur.",
    exampleEn: "What I like the most is the clear structure.",
  },

  // --- 11 words added later ---
  {
    id: "sich-eignen",
    german: "sich eignen",
    english: "to be suited/qualified (for something)",
    exampleDe: "Sie eignet sich gut für diese Aufgabe.",
    exampleEn: "She is well suited for this task.",
  },
  {
    id: "vortrag",
    german: "Vortrag",
    english: "lecture, presentation",
    exampleDe: "Morgen halte ich einen Vortrag über Klimaschutz.",
    exampleEn: "Tomorrow I am giving a lecture on climate protection.",
  },
  {
    id: "sicherheit",
    german: "Sicherheit",
    english: "confidence",
    exampleDe: "Mit der Zeit wächst meine Sicherheit beim Sprechen.",
    exampleEn: "Over time, my confidence in speaking grows.",
  },
  {
    id: "beobachten",
    german: "beobachten",
    english: "to observe",
    exampleDe: "Ich beobachte die Vögel im Garten.",
    exampleEn: "I observe the birds in the garden.",
  },
  {
    id: "sich-fremdschaemen",
    german: "sich fremdschämen",
    english: "to feel secondhand embarrassment (cringe on someone else's behalf)",
    exampleDe: "Ich schäme mich fremd, wenn er so laut spricht.",
    exampleEn: "I feel secondhand embarrassment when he talks so loudly.",
  },
  {
    id: "sich-lohnen",
    german: "sich lohnen",
    english: "to be worth it",
    exampleDe: "Der Aufwand lohnt sich wirklich.",
    exampleEn: "The effort is really worth it.",
  },
  {
    id: "es-weit-bringen",
    german: "es weit bringen",
    english: "to achieve a lot, go far",
    exampleDe: "Mit Fleiß kannst du es weit bringen.",
    exampleEn: "With diligence, you can go far.",
  },
  {
    id: "es-kommt-auf-an",
    german: "Es kommt auf das Wetter an.",
    english: "It depends on the weather.",
    exampleDe: "Ob wir wandern gehen, kommt auf das Wetter an.",
    exampleEn: "Whether we go hiking depends on the weather.",
  },
  {
    id: "es-handelt-sich-um",
    german: "Es handelt sich um den Kundenservice.",
    english: "This is about/concerns customer service.",
    exampleDe: "Es handelt sich um den Kundenservice.",
    exampleEn: "This concerns customer service.",
  },
  {
    id: "ergaenzen",
    german: "ergänzen",
    english: "to add, supplement, complete",
    exampleDe: "Können Sie die Liste noch ergänzen?",
    exampleEn: "Can you still add to / complete the list?",
  },
  {
    id: "entfallen",
    german: "entfallen",
    english: "to be omitted, cancelled, or no longer apply",
    exampleDe: "Der Termin ist entfallen.",
    exampleEn: "The appointment has been cancelled.",
  },

  // --- notebook page 217 (not crossed out; skipped: über verfügen) ---
  {
    id: "ausreden",
    german: "ausreden",
    english: "to finish speaking / to make excuses",
    exampleDe: "Lass mich bitte ausreden.",
    exampleEn: "Please let me finish speaking.",
  },
  {
    id: "jmdn-stoeren",
    german: "jmdn. stören",
    english: "to disturb / interrupt someone",
    exampleDe: "Darf ich Sie kurz stören?",
    exampleEn: "May I disturb you briefly?",
  },
  {
    id: "betreffen",
    german: "betreffen",
    english: "to concern / affect",
    exampleDe: "Das betrifft alle Mitarbeiter.",
    exampleEn: "That concerns all employees.",
  },
  {
    id: "mir-ist-kalt",
    german: "Mir ist kalt.",
    english: "I'm cold.",
    exampleDe: "Kannst du das Fenster schließen? Mir ist kalt.",
    exampleEn: "Can you close the window? I'm cold.",
  },
  {
    id: "beurteilen",
    german: "beurteilen",
    english: "to assess / judge / evaluate",
    exampleDe: "Wie beurteilen Sie die Lage?",
    exampleEn: "How do you assess the situation?",
  },
  {
    id: "zusammenfassung-fazit",
    german: "Zusammenfassung / Fazit",
    english: "summary / conclusion",
    exampleDe: "Zum Schluss kommt eine kurze Zusammenfassung.",
    exampleEn: "At the end there is a short summary.",
  },
  {
    id: "schaetzen",
    german: "schätzen",
    english: "to value / appreciate / estimate",
    exampleDe: "Ich schätze Ihre Unterstützung sehr.",
    exampleEn: "I really appreciate your support.",
  },
  {
    id: "ich-setze-dich-in-cc",
    german: "ich setze dich in CC",
    english: "I'll put you in CC / I'll CC you",
    exampleDe: "Ich setze dich in CC, damit du informiert bleibst.",
    exampleEn: "I'll CC you so you stay informed.",
  },
  {
    id: "gestaltung",
    german: "Gestaltung",
    english: "design / layout / structuring",
    exampleDe: "Die Gestaltung der Präsentation ist klar und modern.",
    exampleEn: "The design of the presentation is clear and modern.",
  },
  {
    id: "abstimmen",
    german: "abstimmen",
    english: "to coordinate / align / vote (on)",
    exampleDe: "Wir müssen den Termin noch abstimmen.",
    exampleEn: "We still need to coordinate the appointment.",
  },
  {
    id: "zu-den-zeiten",
    german: "zu den Zeiten",
    english: "at those times / during those hours",
    exampleDe: "Zu den Zeiten bin ich meistens im Büro.",
    exampleEn: "At those times I am usually in the office.",
  },
  {
    id: "zeitnah",
    german: "zeitnah",
    english: "promptly / in a timely manner",
    exampleDe: "Bitte antworten Sie zeitnah auf die Anfrage.",
    exampleEn: "Please reply to the request promptly.",
  },
  {
    id: "inhaltlich",
    german: "inhaltlich",
    english: "in terms of content / substantively",
    exampleDe: "Inhaltlich ist der Bericht gut, aber zu lang.",
    exampleEn: "In terms of content the report is good, but too long.",
  },
  {
    id: "vorteile",
    german: "Vorteile",
    english: "advantages",
    exampleDe: "Die Vorteile dieses Ansatzes sind klar.",
    exampleEn: "The advantages of this approach are clear.",
  },
  {
    id: "nachteile",
    german: "Nachteile",
    english: "disadvantages",
    exampleDe: "Es gibt auch einige Nachteile.",
    exampleEn: "There are also some disadvantages.",
  },
  {
    id: "aufsicht",
    german: "Aufsicht",
    english: "supervision / oversight",
    exampleDe: "Die Kinder spielen unter Aufsicht.",
    exampleEn: "The children are playing under supervision.",
  },
  {
    id: "stattfinden",
    german: "stattfinden",
    english: "to take place",
    exampleDe: "Das Meeting findet morgen um 10 Uhr statt.",
    exampleEn: "The meeting takes place tomorrow at 10 o'clock.",
  },
  {
    id: "erreichen",
    german: "erreichen",
    english: "to reach / achieve",
    exampleDe: "Wie können wir dieses Ziel erreichen?",
    exampleEn: "How can we achieve this goal?",
  },
  {
    id: "verpflichtend",
    german: "verpflichtend",
    english: "mandatory / obligatory",
    exampleDe: "Die Teilnahme an der Schulung ist verpflichtend.",
    exampleEn: "Participation in the training is mandatory.",
  },
  {
    id: "nachvollziehbarkeit",
    german: "Nachvollziehbarkeit",
    english: "traceability / comprehensibility / auditability",
    exampleDe: "Für die Nachvollziehbarkeit dokumentieren wir jeden Schritt.",
    exampleEn: "For traceability, we document every step.",
  },
  {
    id: "zusammenfassen",
    german: "zusammenfassen",
    english: "to summarize",
    exampleDe: "Können Sie die wichtigsten Punkte zusammenfassen?",
    exampleEn: "Can you summarize the most important points?",
  },
  {
    id: "bezueglich",
    german: "bezüglich",
    english: "regarding / with regard to",
    exampleDe: "Bezüglich Ihres Antrags melden wir uns bald.",
    exampleEn: "Regarding your application, we will get back to you soon.",
  },
  {
    id: "gegenstand",
    german: "Gegenstand",
    english: "subject / object / matter (of discussion)",
    exampleDe: "Der Gegenstand der Besprechung ist der neue Zeitplan.",
    exampleEn: "The subject of the meeting is the new schedule.",
  },
];
